import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {projects,projectBySlug,baseUrl,data} from '@/lib/data';
type Params={params:Promise<{slug:string}>};
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:Params):Promise<Metadata>{const {slug}=await params;const p=projectBySlug(slug);if(!p)return {};return {title:`${p.title} — ${p.category}`,description:p.description,alternates:{canonical:`/projects/${p.slug}/`},openGraph:{type:'article',title:p.title,description:p.description,url:`/projects/${p.slug}/`,images:[{url:p.image,alt:p.imageAlt}]},twitter:{card:'summary_large_image'}}}
export default async function ProjectPage({params}:Params){const {slug}=await params;const p=projectBySlug(slug);if(!p)notFound();const next=projects[(projects.findIndex(x=>x.slug===p.slug)+1)%projects.length];const jsonld={'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.description,image:`${baseUrl}${p.image}`,creator:{'@type':'Person',name:data.profile.name},dateCreated:p.year,url:`${baseUrl}/projects/${p.slug}/`};return <main id="main" className="editorial"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonld).replace(/</g,'\\u003c')}}/><section className="pt-10 md:pt-20"><Link href="/#work" className="label text-muted hover:text-ink">← Back to work</Link><div className="mt-14 grid gap-5 md:grid-cols-12"><div className="label text-muted md:col-span-3">{p.number} / {p.category} / {p.year}</div><div className="md:col-span-9"><h1 className="serif text-[clamp(4rem,10vw,10rem)] leading-[.96]">{p.title}</h1><p className="mt-8 max-w-xl text-xl leading-relaxed text-forest">{p.summary}</p></div></div><div className="mt-14 overflow-hidden bg-[#e0e2db] md:mt-20"><Image src={p.image} alt={p.imageAlt} priority width={1500} height={1100} className="w-full"/></div></section><section className="grid gap-12 border-b rule py-20 md:grid-cols-12 md:py-28"><div className="label text-muted md:col-span-3">The project</div><div className="md:col-span-6"><h2 className="serif text-4xl md:text-6xl">The thinking behind the work.</h2><p className="mt-8 text-lg leading-[1.8] text-forest">{p.description}</p><p className="mt-6 text-base leading-[1.8] text-forest">{p.results}</p>{p.externalUrl&&<a className="mt-8 inline-block border-b border-ink pb-2" href={p.externalUrl} target="_blank" rel="noopener noreferrer">Visit the live project ↗</a>}</div><aside className="md:col-span-3"><h3 className="label mb-5 text-muted">Scope</h3><ul className="mb-9 space-y-2 text-sm">{p.services.map(x=><li key={x}>{x}</li>)}</ul><h3 className="label mb-5 text-muted">Tools & technology</h3><ul className="space-y-2 text-sm">{p.stack.map(x=><li key={x}>{x}</li>)}</ul></aside></section><div className="py-16 md:py-24"><p className="label mb-5 text-muted">Up next</p><Link href={`/projects/${next.slug}/`} className="group flex items-center justify-between gap-6"><span className="serif text-4xl md:text-7xl">{next.title}</span><span className="text-3xl transition-transform group-hover:translate-x-2">↗</span></Link></div></main>}
